# Generated by Django 4.1.5 on 2023-05-22 04:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted at')),
                ('profile_pic', models.ImageField(blank=True, default='default_file/sample.png', upload_to='immovision/images/profile_pics/')),
                ('username', models.CharField(max_length=80, unique=True)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FreelancerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted at')),
                ('active_work', models.IntegerField(blank=True, default=0, null=True)),
                ('total_work', models.IntegerField(blank=True, default=0, null=True)),
                ('total_revenue', models.CharField(default='0.00', max_length=30)),
                ('pending_earn', models.CharField(default='0.00', max_length=30)),
                ('bug_rate', models.IntegerField(blank=True, default=0, null=True)),
                ('late_task', models.IntegerField(blank=True, default=0, null=True)),
                ('status_type', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('not_available', 'Not available'), ('terminated', 'Terminated')], default='active', max_length=60)),
                ('freelancer_status', models.BooleanField(default=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freelancer_profile', to='account.profile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BrokerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted at')),
                ('zuid', models.CharField(blank=True, max_length=255, null=True)),
                ('real_estate_agency', models.CharField(blank=True, max_length=100, null=True)),
                ('website', models.CharField(blank=True, max_length=150, null=True)),
                ('active_orders', models.IntegerField(blank=True, default=0, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broker_profile', to='account.profile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
