# Generated by Django 4.1.5 on 2023-05-10 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreelancerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('deleted_at', models.DateTimeField(null=True, verbose_name='Deleted at')),
                ('active_work', models.IntegerField(blank=True, default=0, null=True)),
                ('total_revenue', models.CharField(max_length=30)),
                ('pending_earn', models.CharField(max_length=30)),
                ('bug_rate', models.IntegerField(blank=True, default=0, null=True)),
                ('late_task', models.IntegerField(blank=True, default=0, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freelancer_profile', to='account.profile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BrokerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('deleted_at', models.DateTimeField(null=True, verbose_name='Deleted at')),
                ('real_estate_agency', models.CharField(blank=True, max_length=100, null=True)),
                ('website', models.CharField(blank=True, max_length=150, null=True)),
                ('active_orders', models.IntegerField(blank=True, default=0, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broker_profile', to='account.profile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
