# Generated by Django 4.1.5 on 2023-07-01 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='payment_info',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
