# Generated by Django 4.1.5 on 2023-07-01 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_profile_payment_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='payment_info',
        ),
    ]
