# Generated by Django 4.1.5 on 2023-05-10 22:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('account', '0002_freelancerprofile_brokerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancerprofile',
            name='status_type',
            field=models.CharField(choices=[('Active', 'active'), ('Suspended', 'suspended'), ('Not available', 'not_available'), ('Terminated', 'terminated')], default=datetime.datetime(2023, 5, 10, 22, 55, 57, 367476, tzinfo=datetime.timezone.utc), max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.address'),
        ),
    ]
