# Generated by Django 4.1.5 on 2023-06-14 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_brokersfilecsv_brokerprofile_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brokerprofile',
            name='language',
            field=models.CharField(blank=True, default='English', max_length=255, null=True),
        ),
    ]
