# Generated by Django 4.1.5 on 2023-06-14 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_brokerprofile_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='brokerprofile',
            name='total_orders',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
