# Generated by Django 4.1.5 on 2023-05-10 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_freelancerprofile_status_type_profile_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancerprofile',
            name='status_type',
            field=models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('not_available', 'Not available'), ('terminated', 'Terminated')], max_length=30),
        ),
    ]
