# Generated by Django 4.1.5 on 2023-07-07 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_ipaddress_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreelancerPaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted at')),
                ('withdrawal_type', models.CharField(choices=[('crypto', 'Crypto'), ('paypal', 'Paypal')], default='paypal', max_length=60)),
                ('paypal_email', models.CharField(blank=True, max_length=20, null=True)),
                ('crypto_address', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='withdraw_info',
            field=models.CharField(blank=True, default=None, max_length=400, null=True),
        ),
        migrations.CreateModel(
            name='FreelancerWithdraw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted at')),
                ('withdraw_amount', models.IntegerField(blank=True, default=0, null=True)),
                ('withdraw_status', models.BooleanField(default=False)),
                ('withdraw_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freelancer_payment_method', to='account.freelancerpaymentmethod')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='freelancerpaymentmethod',
            name='freelancer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freelancer_payment_profile', to='account.freelancerprofile'),
        ),
    ]
