# Generated by Django 4.1.5 on 2023-06-14 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_brokerprofile_total_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancerprofile',
            name='pending_earn',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='freelancerprofile',
            name='total_revenue',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
