# Generated by Django 4.1.5 on 2023-07-07 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_freelancerpaymentmethod_freelancer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancerpaymentmethod',
            name='freelancer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='freelancer_payment_method', to='account.freelancerprofile'),
        ),
    ]
