# Generated by Django 4.1.5 on 2023-07-07 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_freelancerpaymentmethod_freelancer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancerpaymentmethod',
            name='paypal_email',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
