# Generated by Django 4.1.5 on 2023-05-12 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_profile_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancerprofile',
            name='total_work',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
