# Generated by Django 4.1.5 on 2023-06-21 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_paymentmethod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancerprofile',
            name='status_type',
            field=models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('unsuspended', 'Unsuspended'), ('not_available', 'Not available'), ('terminated', 'Terminated')], default='active', max_length=60),
        ),
    ]
