# Generated by Django 4.1.5 on 2023-06-25 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_freelancerprofile_status_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='payment_method_id',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
