# Generated by Django 4.1.5 on 2023-07-07 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_freelancerprofile_total_income'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancerwithdraw',
            name='withdraw_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('complete', 'Complete'), ('cancel', 'Cancel')], default='pending', max_length=70, null=True),
        ),
    ]
