# Generated by Django 4.1.5 on 2023-05-12 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_freelancerprofile_total_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancerprofile',
            name='pending_earn',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='freelancerprofile',
            name='total_revenue',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
