# Generated by Django 4.1.5 on 2023-05-12 19:40

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_freelancerprofile_pending_earn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancerprofile',
            name='pending_earn',
            field=models.CharField(default=datetime.datetime(2023, 5, 12, 19, 40, 21, 472006, tzinfo=datetime.timezone.utc), max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='freelancerprofile',
            name='total_revenue',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
    ]
