# Generated by Django 4.1.5 on 2023-06-25 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_profile_payment_method_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='payment_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
