# Generated by Django 4.1.5 on 2023-07-10 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_freelancerwithdraw_withdraw_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.FileField(blank=True, default='default_file/sample.png', upload_to='immovision/images/profile_pics/'),
        ),
    ]
