# Generated by Django 4.1.5 on 2023-05-14 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_freelancerprofile_pending_earn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brokerprofile',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deleted at'),
        ),
        migrations.AlterField(
            model_name='freelancerprofile',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deleted at'),
        ),
        migrations.AlterField(
            model_name='freelancerprofile',
            name='pending_earn',
            field=models.CharField(default='0.00', max_length=30),
        ),
        migrations.AlterField(
            model_name='freelancerprofile',
            name='total_revenue',
            field=models.CharField(default='0.00', max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deleted at'),
        ),
    ]
