# Generated by Django 4.1.5 on 2023-06-27 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_profile_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='brokerprofile',
            name='is_demo',
            field=models.BooleanField(default=False),
        ),
    ]
