# Generated by Django 4.1.5 on 2023-05-17 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_alter_freelancerprofile_status_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancerprofile',
            name='freelancer_status',
            field=models.BooleanField(default=True),
        ),
    ]
