# Generated by Django 4.1.5 on 2023-08-11 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_alter_profile_profile_pic_profilepicture'),
    ]

    operations = [
        migrations.AddField(
            model_name='brokerprofile',
            name='auto_login',
            field=models.BooleanField(default=True),
        ),
    ]
