# Generated by Django 4.1.5 on 2023-08-20 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_brokerprofile_auto_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='brokerprofile',
            name='realtor_profile_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='brokerprofile',
            name='realtor_uid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
