# Generated by Django 4.1.5 on 2023-05-17 22:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_freelancerprofile_freelancer_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='brokerprofile',
            name='zuid',
            field=models.CharField(default=datetime.datetime(2023, 5, 17, 22, 1, 44, 991498, tzinfo=datetime.timezone.utc), max_length=255),
            preserve_default=False,
        ),
    ]
