# Generated by Django 4.1.5 on 2023-05-18 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_freelancerprofile_freelancer_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='brokerprofile',
            name='zuid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
