# Generated by Django 4.1.5 on 2023-05-20 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_brokerprofile_zuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancerprofile',
            name='status_type',
            field=models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('not_available', 'Not available'), ('terminated', 'Terminated')], default='active', max_length=30),
        ),
    ]
