# Generated by Django 4.1.5 on 2023-05-17 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_brokerprofile_zuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brokerprofile',
            name='zuid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
