# Generated by Django 4.1.5 on 2023-05-22 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_alter_freelancerprofile_status_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancerprofile',
            name='status_type',
            field=models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('not_available', 'Not available'), ('terminated', 'Terminated')], default='active', max_length=60),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(max_length=80, unique=True),
        ),
    ]
