# Generated by Django 4.1.5 on 2023-05-11 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_order_address'),
        ('common', '0002_alter_address_area_alter_address_city_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
