# Generated by Django 4.1.5 on 2023-05-11 10:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0002_remove_order_subtitle_discountcode_bugreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('deleted_at', models.DateTimeField(null=True, verbose_name='Deleted at')),
                ('video_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('video_title', models.CharField(blank=True, max_length=250, null=True)),
                ('subtitle', models.FileField(blank=True, null=True, upload_to='orders/subtitle/')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='orders/videos/')),
                ('privacy_type', models.CharField(choices=[('private', 'Private'), ('public', 'Public')], max_length=30)),
                ('is_demo', models.BooleanField(default=False)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
