# Generated by Django 4.1.5 on 2023-06-21 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_password_reset_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password_reset_token',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
