# Generated by Django 4.1.5 on 2023-05-11 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_user_phone_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.DeleteModel(
            name='Broker',
        ),
        migrations.DeleteModel(
            name='Freelancer',
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('UNSPECIFIED', 'Unspecified'), ('BROKER', 'Broker'), ('FREELANCER', 'Freelancer'), ('ADMIN', 'Admin')], default=('UNSPECIFIED', 'Unspecified'), max_length=20),
        ),
    ]
