# Generated by Django 4.1.5 on 2023-05-22 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_user_email_alter_user_type_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('UNSPECIFIED', 'Unspecified'), ('BROKER', 'Broker'), ('FREELANCER', 'Freelancer'), ('ADMIN', 'Admin')], default='UNSPECIFIED', max_length=80),
        ),
    ]
