# Generated by Django 4.1.5 on 2023-05-31 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(blank=True, choices=[('order', 'Order')], max_length=60, null=True),
        ),
    ]
