# Generated by Django 4.1.5 on 2023-06-01 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
