# Generated by Django 4.1.5 on 2023-06-10 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(blank=True, choices=[('order', 'Order'), ('Broker', 'Broker')], max_length=60, null=True),
        ),
    ]
