# Generated by Django 4.1.5 on 2023-06-17 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(blank=True, choices=[('security', 'Security'), ('alert', 'Alert')], max_length=60, null=True),
        ),
    ]
