# Generated by Django 4.1.5 on 2023-06-21 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0011_contactus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(blank=True, choices=[('security', 'Security'), ('alert', 'Alert'), ('order', 'Order'), ('help', 'Help')], max_length=60, null=True),
        ),
    ]
