# Generated by Django 4.1.5 on 2023-07-02 04:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted at')),
                ('commition', models.CharField(max_length=100)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted at')),
                ('zpid', models.CharField(blank=True, max_length=150, null=True)),
                ('url', models.CharField(max_length=150)),
                ('client_name', models.CharField(max_length=150)),
                ('assistant_type', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=70)),
                ('video_language', models.CharField(choices=[('english', 'English'), ('french', 'French')], max_length=70)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('unpaid', 'Unpaid'), ('pending', 'PENDING'), ('assigned', 'ASSIGNED'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('demo', 'Demo'), ('in_review', 'In Review'), ('canceled', 'Canceled')], max_length=80)),
                ('order_assign_time', models.TimeField(blank=True, null=True)),
                ('payment_status', models.BooleanField(default=False)),
                ('payment_type', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_intent_id', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_method_id', models.CharField(blank=True, max_length=100, null=True)),
                ('apply_subtitle', models.BooleanField(default=True)),
                ('demo_video', models.BooleanField(default=False)),
                ('property_photo_url', models.CharField(blank=True, max_length=300, null=True)),
                ('property_details', models.TextField(blank=True, null=True)),
                ('order_type', models.CharField(blank=True, choices=[('teaser', 'Teaser'), ('full_house', 'Full House')], max_length=80, null=True)),
                ('invoice', models.FileField(blank=True, null=True, upload_to='order/invoices/')),
                ('delivery_time', models.TimeField(blank=True, null=True)),
                ('order_video', models.CharField(blank=True, max_length=145, null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('order_commission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.commition')),
                ('order_receiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.freelancerprofile')),
                ('order_sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.brokerprofile')),
                ('property_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.sellhouseaddress')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MaxOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted at')),
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('max_order', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted at')),
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('valid_date', models.DateField()),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BugReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted at')),
                ('bug_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('bug_details', models.CharField(max_length=600)),
                ('is_solve', models.BooleanField(default=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Amount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted at')),
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('amount', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
