# Generated by Django 4.1.5 on 2023-05-10 23:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0004_alter_freelancerprofile_status_type'),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('deleted_at', models.DateTimeField(null=True, verbose_name='Deleted at')),
                ('commition', models.CharField(max_length=100)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('deleted_at', models.DateTimeField(null=True, verbose_name='Deleted at')),
                ('url', models.CharField(max_length=150)),
                ('client_name', models.CharField(max_length=150)),
                ('assistant_type', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=30)),
                ('video_language', models.CharField(choices=[('english', 'English'), ('french', 'French')], max_length=30)),
                ('subtitle', models.FileField(blank=True, null=True, upload_to='freelancer/videos/subtitle/')),
                ('amount', models.CharField(max_length=100)),
                ('status', models.CharField(blank=True, choices=[('demo', 'Demo'), ('completed', 'Completed'), ('in_progress', 'In Progress'), ('in_review', 'In Review')], max_length=30, null=True)),
                ('payment_status', models.BooleanField(default=False)),
                ('payment_type', models.CharField(max_length=100)),
                ('demo_video', models.BooleanField(default=False)),
                ('order_type', models.CharField(blank=True, choices=[('teaser', 'Teaser'), ('full_house', 'Full House')], max_length=30, null=True)),
                ('invoice', models.FileField(blank=True, null=True, upload_to='order/invoices/')),
                ('delivery_time', models.CharField(blank=True, max_length=20, null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.address')),
                ('order_commission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.commition')),
                ('order_receiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.freelancerprofile')),
                ('order_sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.brokerprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
