# Generated by Django 4.1.5 on 2023-07-14 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='social_media_post',
            field=models.TextField(blank=True, null=True),
        ),
    ]
