# Generated by Django 4.1.5 on 2023-06-09 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_property_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='property_photo',
            field=models.ImageField(blank=True, default='default_file/property_photo.jpg', upload_to='immovision/images/[property_image]/'),
        ),
    ]
