# Generated by Django 4.1.5 on 2023-07-30 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_social_media_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='assistant',
            field=models.BooleanField(default=True),
        ),
    ]
