# Generated by Django 4.1.5 on 2023-06-09 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_property_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='zpid',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
