# Generated by Django 4.1.5 on 2023-08-08 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_assistant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugreport',
            name='bug_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
