# Generated by Django 4.1.5 on 2023-05-17 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_bugreport_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('in_progress', 'In Progress'), ('assigned', 'ASSIGNED'), ('demo', 'Demo'), ('completed', 'Completed'), ('in_review', 'In Review'), ('canceled', 'Canceled')], max_length=30, null=True),
        ),
    ]
