# Generated by Django 4.1.5 on 2023-06-09 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_order_zpid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='property_photo',
        ),
        migrations.AddField(
            model_name='order',
            name='property_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='property_photo_url',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
