# Generated by Django 4.1.5 on 2023-05-19 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_bugreport_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='apply_subtitle',
            field=models.BooleanField(default=True),
        ),
    ]
