# Generated by Django 4.1.5 on 2023-08-11 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_bugreport_bug_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='client_name',
        ),
    ]
