# Generated by Django 4.1.5 on 2023-06-11 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_remove_order_property_photo_order_property_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_video',
            field=models.CharField(blank=True, max_length=145, null=True),
        ),
    ]
