# Generated by Django 4.1.5 on 2023-08-19 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_remove_order_client_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='realtorId',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
