# Generated by Django 4.1.5 on 2023-06-14 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'PENDING'), ('assigned', 'ASSIGNED'), ('in_progress', 'In Progress'), ('video_ready', 'Video is Ready'), ('completed', 'Completed'), ('demo', 'Demo'), ('in_review', 'In Review'), ('is_stack', 'Order In Stack'), ('canceled', 'Canceled')], max_length=80),
        ),
    ]
