# Generated by Django 4.1.5 on 2023-05-19 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'PENDING'), ('assigned', 'ASSIGNED'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('demo', 'Demo'), ('in_review', 'In Review'), ('canceled', 'Canceled')], default=('pending', 'PENDING'), max_length=30),
        ),
    ]
