# Generated by Django 4.1.5 on 2023-05-20 17:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_assign_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 20, 17, 34, 25, 16815, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
