# Generated by Django 4.1.5 on 2023-06-14 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_alter_order_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CancelOrder',
        ),
    ]
