# Generated by Django 4.1.5 on 2023-06-14 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_delete_cancelorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountcode',
            name='code',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'PENDING'), ('assigned', 'ASSIGNED'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('demo', 'Demo'), ('in_review', 'In Review'), ('canceled', 'Canceled')], max_length=80),
        ),
    ]
