# Generated by Django 4.1.5 on 2023-05-20 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_alter_order_order_assign_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_assign_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
