# Generated by Django 4.1.5 on 2023-06-25 18:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_intent_id',
            field=models.CharField(default=datetime.datetime(2023, 6, 25, 18, 39, 34, 964090, tzinfo=datetime.timezone.utc), max_length=100),
            preserve_default=False,
        ),
    ]
