# Generated by Django 4.1.5 on 2023-05-22 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_maxorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='assistant_type',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=70),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(blank=True, choices=[('teaser', 'Teaser'), ('full_house', 'Full House')], max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'PENDING'), ('assigned', 'ASSIGNED'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('demo', 'Demo'), ('in_review', 'In Review'), ('canceled', 'Canceled')], max_length=80),
        ),
        migrations.AlterField(
            model_name='order',
            name='video_language',
            field=models.CharField(choices=[('english', 'English'), ('french', 'French')], max_length=70),
        ),
    ]
