# Generated by Django 4.1.5 on 2023-06-25 21:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_alter_order_payment_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Earning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted at')),
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('total_earning', models.CharField(max_length=600)),
                ('pending_earning', models.CharField(max_length=600)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
