# Generated by Django 4.1.5 on 2023-06-25 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_profile_payment_type'),
        ('order', '0017_earning'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Earning',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.brokerprofile'),
        ),
    ]
