# Generated by Django 4.1.5 on 2023-06-26 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0018_delete_earning_alter_order_order_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
